default:
  image: docker:stable
  before_script:
  - docker login -u admin -p $NEXUS_PASSWORD registry:5000
  - apk add make
  - if [ '$CI_COMMIT_REF_NAME =~ /^(release\/.*)$/' ]; then export VERSION="${CI_COMMIT_REF_NAME}"; else export VERSION="${CI_COMMIT_SHORT_SHA}"; fi
  variables:
    DOCKER_IMAGE: "registry:5000/$CI_PROJECT_NAME"
    VERSION: "$(CI_COMMIT_HASH)"
  
stages:
  - build_base_application
  - build_application
  - publish

build_base:
  stage: build_base_application
  script:
    - docker build -t $DOCKER_IMAGE_PROJECT/base:$VERSION .
    - docker push $DOCKER_IMAGE_PROJECT/base:$VERSION

#loop for builds
for project in (gateway, products, orders)
do
build_${project}:
  stage: build_application
  script:
    - sed -i "s/FROM desatranques\/base/FROM $DOCKER_REGISTRY\/$CI_PROJECT_NAME\/base:$VERSION/g" ${project}/Dockerfile
    - docker build -t $DOCKER_IMAGE_PROJECT/${project}:$VERSION ${project}/
    - docker push $DOCKER_IMAGE_PROJECT/${project}:$VERSION
done

#loop for builds
for project in (gateway, products, orders)
do
publish_${project}:
  stage: publish
  script:
    - sed -i "s/FROM desatranques\/base/FROM $DOCKER_REGISTRY\/$CI_PROJECT_NAME\/base:$VERSION/g" ${project}/Dockerfile
    - docker build -t $DOCKER_IMAGE_PROJECT/${project}:$VERSION ${project}/
    - docker push $DOCKER_IMAGE_PROJECT/${project}:$VERSION
  only:
    - master
done