variables:
    DOCKER_IMAGE: "registry:5000/$CI_PROJECT_NAME"
    DOCKER_REGISTRY: "registry:5000"
    TEMPORAL_VERSION: "TEMPORAL_${CI_COMMIT_SHA}"
    PROJECT: "gateway"
default:
  
  before_script:
  - docker login -u admin -p $NEXUS_PASSWORD registry:5000
  - apk add make
  - apk update && apk add bash

stages:
  - build_base_application
  - build_application
  - publish

build_base:
  stage: build_base_application
  script:
    - make make-base 

build_gateway:
  stage: build_application
  script:
    - make PROJECT="gateway" make-application 
build_products:
  stage: build_application
  script:
    - make PROJECT="products" make-application 
build_orders:
  stage: build_application
  script:
    - make PROJECT="orders" make-application 

publish_gateway:
  stage: publish
  script:
    - /bin/bash
    - if [[ $CI_COMMIT_REF_NAME == release* ]]; then export VERSION="${CI_COMMIT_REF_NAME#*/}"; else export VERSION="${CI_COMMIT_SHA}"; fi
    - echo $VERSION
    - make PROJECT="gateway" make-publish 


      