version: "3.4"
services:
  rabbit:
    image: rabbitmq:3.7-management
    ports:
    - "15672:15672"

  redis:
    image: redis:5.0

  products:
    image: desatranques/products
    depends_on:
      - rabbit
      - redis
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_INDEX: "11"
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"
