version: "3.4"
services:
  rabbit:
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
    env_file:
      - rabbit.env  

  gateway:
    image: desatranques/gateway
    depends_on:
      - rabbit
    ports:
      - "8003:8000"
    env_file:
      - rabbit.env

  postgres:
      image: postgres:11.5
      env_file:
        - postgres.env

  orders:
    image: desatranques/orders
    depends_on:
      - rabbit
      - postgres
    env_file:
      - postgres.env
      - rabbit.env

  redis:
    image: redis:5.0
    env_file:
      - redis.env
      
  products:
    image: desatranques/products
    depends_on:
      - rabbit
      - redis
    env_file:
      - redis.env
      - rabbit.env
