version: "3.4"
services:
  rabbit:
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"

  gateway:
    image: desatranques/gateway
    depends_on:
      - rabbit
    ports:
      - "8003:8000"
    env_file:
      - rabbit.env
