version: "3.4"
services:
  rabbit:
    image: rabbitmq:3.7-management
    ports:
        - "15672:15672" # Exposing RabbitMQ web management on different port for convenience

  postgres:
    image: postgres:11.5
    env_file: 
        - postgres.env

  redis:
    image: redis:5.0

  orders:
    build:
        context: orders/
    depends_on:
      - rabbit
      - postgres
    env_file: 
        - orders/orders.env
    # volumes:
    #     - ./orders/:/var/nameko/

  products:
    build:
        context: products/
    depends_on:
      - rabbit
      - redis
    env_file:
      - products/products.env
    
    # volumes:
    #     - ./products/:/var/nameko/

  gateway:
    build:
        context: gateway/
    depends_on:
      - rabbit
      
    ports:
        - "8003:8000"
    env_file:
      - gateway/gateway.env
        
    # volumes:
    #     - ./gateway/:/var/nameko/

