version: "3.4"
services:
  rabbit:
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
    env_file:
      - rabbit.env

  redis:
    image: redis:5.0
    env_file:
      - redis.env
  products:
    image: desatranques/products
    depends_on:
      - rabbit
      - redis
    env_file:
      - rabbit.env
      - redis.env
