version: "3.4"
services:
  rabbit:
    image: rabbitmq:3.7-management
    ports:
    - "15672:15672"

  redis:
    image: redis:5.0

  products:
    image: desatranques/products
    depends_on:
      - rabbit
      - redis
    env_file:
      - redis.env
      - rabbit.env