version: "3.4"
services:
  rabbit:
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
    env_file:
      - rabbit.env
      
  postgres:
    image: postgres:11.5
    env_file:
      - postgres.env

  orders:
    image: desatranques/orders
    depends_on:
      - rabbit
      - postgres
    env_file:
      - postgres.env
      - rabbit.env