version: "3.4"
services:
  rabbit:
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
    environment:
      DB_PASSWORD: "password"
      DB_USER: "postgres"
      DB_HOST: "postgres"
      DB_NAME: "orders"
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_INDEX: "11"
      REDIS_PASSWORD: "password"
      
  redis:
    image: redis:5.0
    environment:
      DB_PASSWORD: "password"
      DB_USER: "postgres"
      DB_HOST: "postgres"
      DB_NAME: "orders"
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_INDEX: "11"
      REDIS_PASSWORD: "password"
  
  products:
    image: desatranques/products
    depends_on:
      - rabbit
      - redis
    environment:
      DB_PASSWORD: "password"
      DB_USER: "postgres"
      DB_HOST: "postgres"
      DB_NAME: "orders"
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_INDEX: "11"
      REDIS_PASSWORD: "password"