AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASSWORD:guest}@${RABBIT_HOST:localhost}:${RABBIT_PORT:5672}/

RABBIT_API_URI: http://${RABBIT_USER:guest}:${RABBIT_PASSWORD:guest}@${RABBIT_HOST:localhost}:${RABBIT_MANAGEMENT_PORT:15672}

REDIS_URI: redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}/${REDIS_INDEX:11}